[Noetic] Add missing dependency on yaml-cpp
Maybe this will fix https://build.ros.org/job/Nbin_uF64__face_detector__ubuntu_focal_amd64__binary/9

Which failed with

```
23:05:39 /tmp/binarydeb/ros-noetic-face-detector-1.4.0/src/face_detection.cpp:79:10: fatal error: yaml-cpp/yaml.h: No such file or directory
23:05:41    79 | #include <yaml-cpp/yaml.h>
23:05:41       |          ^~~~~~~~~~~~~~~~~
```

https://index.ros.org/d/yaml-cpp/